package com.karthik.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.stereotype.Component;
import springfox.documentation.builders.ApiInfoBuilder;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

import static springfox.documentation.builders.PathSelectors.regex;

@EnableSwagger2
@Configuration
public class SwaggerConfig {

    @Bean
    public Docket postApi() {
        return new Docket(DocumentationType.SWAGGER_2).groupName("karthik rajan").apiInfo(apiInfo())
                .select().paths(regex("/api/employee.*")).build();
    }

    private ApiInfo apiInfo(){
        return new ApiInfoBuilder().title("User Service")
                .description("Sample Documentation Generated by Swagger")
                .version("1.0")
                .build();
    }
}
